apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rgate
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$3
spec:
  rules:
    - host: rgate
      http:
        paths:
          - path: /api/payments/
            pathType: Prefix
            backend:
              service:
                name: payments
                port:
                  number: 80
          - path: /api/orders/
            pathType: Prefix
            backend:
              service:
                name: orders
                port:
                  number: 80
