apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rgate
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$3
spec:
  rules:
    - host: {{ .Values.rgate.name }}
      http:
        paths:
          - path: /api/payments/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.rgate.backend1.name }}
                port:
                  number: 8080
          - path: /api/orders/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.rgate.backend2.name }}
                port:
                  number: 8080
