apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.payments.name }}
  labels:
    app: {{ .Values.payments.name }}
spec:
  replicas: {{ .Values.payments.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.payments.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.payments.name }}
    spec:
      containers:
      - name: {{ .Values.payments.name }}
        image: {{ .Values.payments.ImageName }}
        ports:
        - containerPort: {{ .Values.payments.containerPort }}
